language: node_js
sudo: false
dist: trusty
node_js:
- v10.18.0
git:
  depth: 10
addons:
  ssh_known_hosts:
  - 39.104.123.222
  - github.com
install:
- sudo apt-get install sshpass
script:
- "npm run build"
deploy:
  provider: script
  script: sh -x deploy.sh
  skip_cleanup: true
  on:
    branch: master
