language: go
sudo: false
dist: trusty
go:
- 1.x
git:
  depth: 10
addons:
  ssh_known_hosts:
  - 39.104.123.222
  - github.com
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_0.69.0_Linux-64bit.tar.gz
- tar -xzvf hugo_0.69.0_Linux-64bit.tar.gz
- sudo apt-get install sshpass
script:
- "./hugo"
after_script:
  - pwd
  - sshpass -p $SPW scp -o stricthostkeychecking=no -r ./public/* root@39.104.123.222:/opt/dumi
