language: node_js
sudo: false
dist: trusty
node_js:
- 10.x
git:
  depth: 10
addons:
  ssh_known_hosts:
  - 39.104.123.222
  - github.com
install:
# - sudo apt-get install sshpass
script:
- "ls"
- "pwd"
deploy:
  skip_cleanup: true
  on:
    branch: master
