baseURL = "https://algorithm.elixir-zh.cn/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Terryzh 的算法小屋"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"
# [UA-XXXXXXXX-X] 谷歌分析代号
googleAnalytics = "UA-161994395-1"
# 是否使用 emoji 代码
enableEmoji = true

[params]
  # LoveIt theme version
  version = "0.1.X"
  description = "This is My New Hugo Site"
  # Header info
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
  # Footer Copyright Info
  [params.footer]
    # Site creation time
    since = 2019
    # ICP info only in China (HTML format is allowed)
    icp = ""
    # license info (HTML format is allowed)
    license= '<a rel="license external nofollow noopener noreffer" href="http://www.beian.miit.gov.cn/" target="_blank">黔ICP备19003627号</a>'
  # Home Page Info
  [params.home]
    # Home Page Profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "http://img.elixir-zh.cn/uPic/algorithm_favicon.svg"
      # subtitle shown in home page
      subtitle = "算法从入坑到入土系列"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
  # Social Info in home page
  [params.social]
    GitHub = "https://github.com/Terry-bear"
    Email = "496971418@qq.com"
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    blockLeftDelimiter = "$$"
    blockRightDelimiter = "$$"
    # default inline delimiter is $ ... $ and \\( ... \\)
    inlineLeftDelimiter = "$"
    inlineRightDelimiter = "$"
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # Comment Config
  [params.comment]
    enable = true
    # Disqus Comment Config (https://disqus.com/)
    # Gitalk Comment Config (https://github.com/gitalk/gitalk)
    [params.comment.gitalk]
      # LoveIt   v0.1.1
      enable = true
      owner = "Terry-bear"
      repo = "blog_comments"
      clientId = "bf0ed9ea18e819e40135"
      clientSecret = "92bdc65717aa7f0ec48bfe94e773b57a21163785"
  # CSS and JS Files CDN
  [params.cdn]
    enable = true
    # katex@0.11.1 https://github.com/KaTeX/KaTeX
    katexCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" integrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/+DiW/UqRcLbRjq" crossorigin="anonymous">'
    katexJS = '<script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js" integrity="sha384-y23I5Q6l+B6vatafAwxRu/0oK/79VlbSz7Q9aiSZUvyWYIYsd+qj+o24G5ZU2zJz" crossorigin="anonymous"></script>'
    katexAutoRenderJS = '<script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>'
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is allowed), such as icons
    pre = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
    
# Sitemap Info
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
[author]
  name = "Terryzh"
  homepage = "https://www.elixir-zh.cn/"
