# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: ~/algorithmBlog
    steps:
      - add_ssh_keys:
          fingerprints:
            - "12:f5:c2:06:47:47:63:f6:31:50:7f:61:db:ec:22:e8"
      - checkout
      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_0.69.0_Linux-64bit.tar.gz
      - run: sudo apt-get install sshpass
      - run: tar -xzvf hugo_0.69.0_Linux-64bit.tar.gz
      - run: ./hugo
      - run: ssh -v root@39.104.123.222
      - run: bash ./.circleci/deploy.sh
