# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: ~/algorithmBlog
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7b:b1:2f:80:5d:30:37:9a:36:88:16:6a:39:8f:2e:4c"
      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_0.69.0_Linux-64bit.tar.gz
      - run: tar -xzvf hugo_0.69.0_Linux-64bit.tar.gz
      - run: ./hugo
  deploy:
    machine:
      timezone:
        Asia/Shanghai # 设置上海时区
      enabled: true
    working_directory: ~/algorithmBlog
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: pwd && ls -al
      - run:
          name: Deploy Over SSH
          command: ./.circleci/deploy.sh
      - run: echo "====================部署完毕=============================="
